# Generated by Django 4.1.5 on 2023-01-11 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 18, 58, 21, 634941, tzinfo=datetime.timezone.utc), verbose_name='Member since'),
        ),
    ]
